-- Migration: Atualizar payload_template dos webhooks de carnê com formato correto
-- O sistema espera: {"template": "mensagem", "campos": {"chave": "valor"}}

UPDATE webhooks SET payload_template = '{"template":"Novo carnê #{{carne_id}} criado para {{cliente_nome}} - {{quantidade_parcelas}}x de {{valor_parcela}} - Pedido #{{pedido_id}}","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","quantidade_parcelas":"{{quantidade_parcelas}}","total_geral":"{{total_geral}}","valor_parcela":"{{valor_parcela}}","primeiro_vencimento":"{{primeiro_vencimento}}","data_criacao":"{{data}}"}}' WHERE nome = 'carne_criado';

UPDATE webhooks SET payload_template = '{"template":"Cobrança: Parcela {{numero_parcela}}/{{total_parcelas}} do Carnê #{{carne_id}} - {{cliente_nome}} - Vencimento: {{vencimento}} - Valor: {{valor_parcela}}","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","numero_parcela":"{{numero_parcela}}","total_parcelas":"{{total_parcelas}}","parcelas_pagas":"{{parcelas_pagas}}","valor_parcela":"{{valor_parcela}}","valor_produtos":"{{valor_produtos}}","valor_taxas":"{{valor_taxas}}","vencimento":"{{vencimento}}","dias_atraso":"{{dias_atraso}}","total_geral":"{{total_geral}}","data":"{{data}}"}}' WHERE nome = 'carne_cobranca';

UPDATE webhooks SET payload_template = '{"template":"Lembrete: Parcela {{numero_parcela}}/{{total_parcelas}} do Carnê #{{carne_id}} vence em {{vencimento}} - {{cliente_nome}} - Valor: {{valor_parcela}}","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","numero_parcela":"{{numero_parcela}}","total_parcelas":"{{total_parcelas}}","parcelas_pagas":"{{parcelas_pagas}}","valor_parcela":"{{valor_parcela}}","vencimento":"{{vencimento}}","total_geral":"{{total_geral}}","data":"{{data}}"}}' WHERE nome = 'carne_parcela_proxima_vencimento';

UPDATE webhooks SET payload_template = '{"template":"Pagamento confirmado: Parcela {{numero_parcela}}/{{total_parcelas}} do Carnê #{{carne_id}} - {{cliente_nome}} - {{valor_parcela}} - Pagas: {{parcelas_pagas}}/{{total_parcelas}}","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","numero_parcela":"{{numero_parcela}}","total_parcelas":"{{total_parcelas}}","parcelas_pagas":"{{parcelas_pagas}}","valor_parcela":"{{valor_parcela}}","valor_produtos":"{{valor_produtos}}","valor_taxas":"{{valor_taxas}}","total_geral":"{{total_geral}}","valor_pago_total":"{{valor_pago_total}}","valor_restante":"{{valor_restante}}","data":"{{data}}"}}' WHERE nome = 'carne_pagamento_confirmado';

UPDATE webhooks SET payload_template = '{"template":"Carnê #{{carne_id}} QUITADO! {{cliente_nome}} - {{quantidade_parcelas}} parcelas pagas - Total: {{total_geral}} - Pedido #{{pedido_id}}","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","quantidade_parcelas":"{{quantidade_parcelas}}","total_geral":"{{total_geral}}","data":"{{data}}"}}' WHERE nome = 'carne_quitado';

UPDATE webhooks SET payload_template = '{"template":"Envio liberado! Carnê #{{carne_id}} - Pedido #{{pedido_id}} - {{cliente_nome}} - Produto será preparado para envio","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","quantidade_parcelas":"{{quantidade_parcelas}}","total_geral":"{{total_geral}}","data":"{{data}}"}}' WHERE nome = 'carne_envio_liberado';

UPDATE webhooks SET payload_template = '{"template":"AVISO CANCELAMENTO: Carnê #{{carne_id}} - {{cliente_nome}} - {{parcelas_atrasadas}} parcelas em atraso ({{dias_atraso}} dias) - Regularize para evitar cancelamento","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","parcelas_atrasadas":"{{parcelas_atrasadas}}","dias_atraso":"{{dias_atraso}}","total_parcelas":"{{total_parcelas}}","parcelas_pagas":"{{parcelas_pagas}}","total_geral":"{{total_geral}}","data":"{{data}}"}}' WHERE nome = 'carne_aviso_cancelamento';

UPDATE webhooks SET payload_template = '{"template":"CANCELADO: Carnê #{{carne_id}} - {{cliente_nome}} - Cancelado por inadimplência - Parcelas pagas: {{parcelas_pagas}}/{{total_parcelas}}","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","parcelas_pagas":"{{parcelas_pagas}}","total_parcelas":"{{total_parcelas}}","total_geral":"{{total_geral}}","motivo":"inadimplencia","data":"{{data}}"}}' WHERE nome = 'carne_cancelado';
