-- Migration: Atualizar templates de mensagem dos webhooks de carnê para serem mais explicativos

-- Garantir que a tabela suporta emojis (utf8mb4)
ALTER TABLE webhooks CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

UPDATE webhooks SET payload_template = '{"template":"📋 *Carnê Criado*\\n\\nOlá! O carnê #{{carne_id}} foi criado com sucesso para o cliente *{{cliente_nome}}*.\\n\\n📦 Pedido: #{{pedido_id}}\\n💳 Parcelas: {{quantidade_parcelas}}x de {{valor_parcela}}\\n💰 Total: {{total_geral}}\\n📅 Primeiro vencimento: {{primeiro_vencimento}}\\n\\nO cliente já pode acessar o carnê e realizar o pagamento da primeira parcela.","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","quantidade_parcelas":"{{quantidade_parcelas}}","total_geral":"{{total_geral}}","valor_parcela":"{{valor_parcela}}","primeiro_vencimento":"{{primeiro_vencimento}}","data_criacao":"{{data}}"}}' WHERE nome = 'carne_criado';

UPDATE webhooks SET payload_template = '{"template":"🔴 *Cobrança de Parcela*\\n\\nA parcela {{numero_parcela}} de {{total_parcelas}} do carnê #{{carne_id}} está pendente de pagamento.\\n\\n👤 Cliente: {{cliente_nome}}\\n📧 Email: {{cliente_email}}\\n📦 Pedido: #{{pedido_id}}\\n\\n💳 Valor da parcela: {{valor_parcela}}\\n   • Produtos: {{valor_produtos}}\\n   • Taxas/Impostos: {{valor_taxas}}\\n📅 Vencimento: {{vencimento}}\\n⏰ Dias em atraso: {{dias_atraso}}\\n\\n📊 Progresso: {{parcelas_pagas}}/{{total_parcelas}} parcelas pagas\\n💰 Total do carnê: {{total_geral}}","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","numero_parcela":"{{numero_parcela}}","total_parcelas":"{{total_parcelas}}","parcelas_pagas":"{{parcelas_pagas}}","valor_parcela":"{{valor_parcela}}","valor_produtos":"{{valor_produtos}}","valor_taxas":"{{valor_taxas}}","vencimento":"{{vencimento}}","dias_atraso":"{{dias_atraso}}","total_geral":"{{total_geral}}","data":"{{data}}"}}' WHERE nome = 'carne_cobranca';

UPDATE webhooks SET payload_template = '{"template":"⚠️ *Lembrete de Vencimento*\\n\\nA parcela {{numero_parcela}} de {{total_parcelas}} do carnê #{{carne_id}} vence em breve!\\n\\n👤 Cliente: {{cliente_nome}}\\n📧 Email: {{cliente_email}}\\n📦 Pedido: #{{pedido_id}}\\n\\n💳 Valor: {{valor_parcela}}\\n📅 Vencimento: {{vencimento}}\\n\\n📊 Progresso: {{parcelas_pagas}}/{{total_parcelas}} parcelas pagas\\n💰 Total do carnê: {{total_geral}}\\n\\nLembre o cliente de efetuar o pagamento para manter o carnê em dia.","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","numero_parcela":"{{numero_parcela}}","total_parcelas":"{{total_parcelas}}","parcelas_pagas":"{{parcelas_pagas}}","valor_parcela":"{{valor_parcela}}","vencimento":"{{vencimento}}","total_geral":"{{total_geral}}","data":"{{data}}"}}' WHERE nome = 'carne_parcela_proxima_vencimento';

UPDATE webhooks SET payload_template = '{"template":"✅ *Pagamento Confirmado*\\n\\nA parcela {{numero_parcela}} de {{total_parcelas}} do carnê #{{carne_id}} foi paga com sucesso!\\n\\n👤 Cliente: {{cliente_nome}}\\n📧 Email: {{cliente_email}}\\n📦 Pedido: #{{pedido_id}}\\n\\n💳 Valor pago: {{valor_parcela}}\\n   • Produtos: {{valor_produtos}}\\n   • Taxas/Impostos: {{valor_taxas}}\\n\\n📊 Progresso: {{parcelas_pagas}}/{{total_parcelas}} parcelas pagas\\n💰 Total pago até agora: {{valor_pago_total}}\\n💰 Restante: {{valor_restante}}\\n💰 Total do carnê: {{total_geral}}","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","numero_parcela":"{{numero_parcela}}","total_parcelas":"{{total_parcelas}}","parcelas_pagas":"{{parcelas_pagas}}","valor_parcela":"{{valor_parcela}}","valor_produtos":"{{valor_produtos}}","valor_taxas":"{{valor_taxas}}","total_geral":"{{total_geral}}","valor_pago_total":"{{valor_pago_total}}","valor_restante":"{{valor_restante}}","data":"{{data}}"}}' WHERE nome = 'carne_pagamento_confirmado';

UPDATE webhooks SET payload_template = '{"template":"🎉 *Carnê Quitado!*\\n\\nParabéns! O carnê #{{carne_id}} foi totalmente quitado!\\n\\n👤 Cliente: {{cliente_nome}}\\n📧 Email: {{cliente_email}}\\n📦 Pedido: #{{pedido_id}}\\n\\n✅ Todas as {{quantidade_parcelas}} parcelas foram pagas\\n💰 Total quitado: {{total_geral}}\\n\\nO produto está liberado para preparação e envio.","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","quantidade_parcelas":"{{quantidade_parcelas}}","total_geral":"{{total_geral}}","data":"{{data}}"}}' WHERE nome = 'carne_quitado';

UPDATE webhooks SET payload_template = '{"template":"🚀 *Envio Liberado!*\\n\\nO envio do produto do carnê #{{carne_id}} foi liberado!\\n\\n👤 Cliente: {{cliente_nome}}\\n📧 Email: {{cliente_email}}\\n📦 Pedido: #{{pedido_id}}\\n\\n✅ Carnê quitado ({{quantidade_parcelas}} parcelas)\\n💰 Total: {{total_geral}}\\n\\nO produto será preparado para envio. O cliente receberá o código de rastreamento em breve.","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","quantidade_parcelas":"{{quantidade_parcelas}}","total_geral":"{{total_geral}}","data":"{{data}}"}}' WHERE nome = 'carne_envio_liberado';

UPDATE webhooks SET payload_template = '{"template":"🚨 *AVISO DE CANCELAMENTO*\\n\\nO carnê #{{carne_id}} está prestes a ser cancelado por inadimplência!\\n\\n👤 Cliente: {{cliente_nome}}\\n📧 Email: {{cliente_email}}\\n📦 Pedido: #{{pedido_id}}\\n\\n❌ Parcelas em atraso: {{parcelas_atrasadas}}\\n⏰ Dias em atraso: {{dias_atraso}}\\n📊 Progresso: {{parcelas_pagas}}/{{total_parcelas}} parcelas pagas\\n💰 Total do carnê: {{total_geral}}\\n\\nSe o pagamento não for regularizado nos próximos dias, o carnê será cancelado automaticamente.","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","parcelas_atrasadas":"{{parcelas_atrasadas}}","dias_atraso":"{{dias_atraso}}","total_parcelas":"{{total_parcelas}}","parcelas_pagas":"{{parcelas_pagas}}","total_geral":"{{total_geral}}","data":"{{data}}"}}' WHERE nome = 'carne_aviso_cancelamento';

UPDATE webhooks SET payload_template = '{"template":"❌ *Carnê Cancelado*\\n\\nO carnê #{{carne_id}} foi cancelado por inadimplência.\\n\\n👤 Cliente: {{cliente_nome}}\\n📧 Email: {{cliente_email}}\\n📦 Pedido: #{{pedido_id}}\\n\\n📊 Parcelas pagas antes do cancelamento: {{parcelas_pagas}}/{{total_parcelas}}\\n💰 Total do carnê: {{total_geral}}\\n📌 Motivo: Inadimplência prolongada\\n\\nO produto não será enviado. Os valores já pagos não serão reembolsados conforme os termos aceitos.","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","parcelas_pagas":"{{parcelas_pagas}}","total_parcelas":"{{total_parcelas}}","total_geral":"{{total_geral}}","motivo":"inadimplencia","data":"{{data}}"}}' WHERE nome = 'carne_cancelado';
