-- Migration: Corrigir mensagens dos webhooks de carnê para tom direcionado ao cliente

UPDATE webhooks SET payload_template = '{"template":"Ola, {{cliente_nome}}! Seu carne foi criado com sucesso.\\n\\nPedido: #{{pedido_id}}\\nParcelas: {{quantidade_parcelas}}x de {{valor_parcela}}\\nTotal: {{total_geral}}\\nPrimeiro vencimento: {{primeiro_vencimento}}\\n\\nAcesse sua area para visualizar as parcelas e realizar o pagamento.","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","quantidade_parcelas":"{{quantidade_parcelas}}","total_geral":"{{total_geral}}","valor_parcela":"{{valor_parcela}}","primeiro_vencimento":"{{primeiro_vencimento}}","data_criacao":"{{data}}"}}' WHERE nome = 'carne_criado';

UPDATE webhooks SET payload_template = '{"template":"Ola, {{cliente_nome}}. Sua parcela {{numero_parcela}} de {{total_parcelas}} esta pendente de pagamento.\\n\\nPedido: #{{pedido_id}}\\nValor da parcela: {{valor_parcela}}\\n  - Produtos: {{valor_produtos}}\\n  - Taxas e impostos: {{valor_taxas}}\\nVencimento: {{vencimento}}\\n\\nRegularize o pagamento para evitar o cancelamento do seu carne. Acesse sua area para pagar.","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","numero_parcela":"{{numero_parcela}}","total_parcelas":"{{total_parcelas}}","parcelas_pagas":"{{parcelas_pagas}}","valor_parcela":"{{valor_parcela}}","valor_produtos":"{{valor_produtos}}","valor_taxas":"{{valor_taxas}}","vencimento":"{{vencimento}}","dias_atraso":"{{dias_atraso}}","total_geral":"{{total_geral}}","data":"{{data}}"}}' WHERE nome = 'carne_cobranca';

UPDATE webhooks SET payload_template = '{"template":"Ola, {{cliente_nome}}! Lembrete: sua parcela {{numero_parcela}} de {{total_parcelas}} vence em {{vencimento}}.\\n\\nPedido: #{{pedido_id}}\\nValor: {{valor_parcela}}\\nProgresso: {{parcelas_pagas}} de {{total_parcelas}} parcelas pagas\\n\\nRealize o pagamento para manter seu carne em dia e evitar cobrancas adicionais.","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","numero_parcela":"{{numero_parcela}}","total_parcelas":"{{total_parcelas}}","parcelas_pagas":"{{parcelas_pagas}}","valor_parcela":"{{valor_parcela}}","vencimento":"{{vencimento}}","total_geral":"{{total_geral}}","data":"{{data}}"}}' WHERE nome = 'carne_parcela_proxima_vencimento';

UPDATE webhooks SET payload_template = '{"template":"Ola, {{cliente_nome}}! Recebemos seu pagamento da parcela {{numero_parcela}} de {{total_parcelas}}.\\n\\nPedido: #{{pedido_id}}\\nValor pago: {{valor_parcela}}\\n  - Produtos: {{valor_produtos}}\\n  - Taxas e impostos: {{valor_taxas}}\\n\\nProgresso: {{parcelas_pagas}} de {{total_parcelas}} parcelas pagas\\nTotal pago ate agora: {{valor_pago_total}}\\nRestante: {{valor_restante}}\\n\\nObrigado por manter seu carne em dia!","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","numero_parcela":"{{numero_parcela}}","total_parcelas":"{{total_parcelas}}","parcelas_pagas":"{{parcelas_pagas}}","valor_parcela":"{{valor_parcela}}","valor_produtos":"{{valor_produtos}}","valor_taxas":"{{valor_taxas}}","total_geral":"{{total_geral}}","valor_pago_total":"{{valor_pago_total}}","valor_restante":"{{valor_restante}}","data":"{{data}}"}}' WHERE nome = 'carne_pagamento_confirmado';

UPDATE webhooks SET payload_template = '{"template":"Parabens, {{cliente_nome}}! Seu carne foi totalmente quitado!\\n\\nPedido: #{{pedido_id}}\\nParcelas pagas: {{quantidade_parcelas}}\\nTotal quitado: {{total_geral}}\\n\\nSeu produto sera preparado para envio em breve. Voce recebera uma notificacao com o codigo de rastreamento assim que for despachado.","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","quantidade_parcelas":"{{quantidade_parcelas}}","total_geral":"{{total_geral}}","data":"{{data}}"}}' WHERE nome = 'carne_quitado';

UPDATE webhooks SET payload_template = '{"template":"Ola, {{cliente_nome}}! Otima noticia: o envio do seu produto foi liberado!\\n\\nPedido: #{{pedido_id}}\\nCarne: #{{carne_id}} ({{quantidade_parcelas}} parcelas quitadas)\\nTotal: {{total_geral}}\\n\\nSeu produto esta sendo preparado para envio. Em breve voce recebera o codigo de rastreamento.","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","quantidade_parcelas":"{{quantidade_parcelas}}","total_geral":"{{total_geral}}","data":"{{data}}"}}' WHERE nome = 'carne_envio_liberado';

UPDATE webhooks SET payload_template = '{"template":"Ola, {{cliente_nome}}. Seu carne #{{carne_id}} esta prestes a ser cancelado por falta de pagamento.\\n\\nPedido: #{{pedido_id}}\\nParcelas em atraso: {{parcelas_atrasadas}}\\nDias em atraso: {{dias_atraso}}\\nProgresso: {{parcelas_pagas}} de {{total_parcelas}} parcelas pagas\\n\\nSe o pagamento nao for regularizado nos proximos dias, o carne sera cancelado automaticamente e o produto nao sera enviado.\\n\\nEntre em contato conosco se precisar de ajuda.","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","parcelas_atrasadas":"{{parcelas_atrasadas}}","dias_atraso":"{{dias_atraso}}","total_parcelas":"{{total_parcelas}}","parcelas_pagas":"{{parcelas_pagas}}","total_geral":"{{total_geral}}","data":"{{data}}"}}' WHERE nome = 'carne_aviso_cancelamento';

UPDATE webhooks SET payload_template = '{"template":"Ola, {{cliente_nome}}. Infelizmente seu carne #{{carne_id}} foi cancelado por falta de pagamento.\\n\\nPedido: #{{pedido_id}}\\nParcelas pagas antes do cancelamento: {{parcelas_pagas}} de {{total_parcelas}}\\nTotal do carne: {{total_geral}}\\n\\nO produto nao sera enviado. Se voce acredita que houve um erro ou deseja mais informacoes, entre em contato com nosso suporte.","campos":{"carne_id":"{{carne_id}}","pedido_id":"{{pedido_id}}","cliente_nome":"{{cliente_nome}}","cliente_email":"{{cliente_email}}","parcelas_pagas":"{{parcelas_pagas}}","total_parcelas":"{{total_parcelas}}","total_geral":"{{total_geral}}","motivo":"inadimplencia","data":"{{data}}"}}' WHERE nome = 'carne_cancelado';
